// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _fr = {
  "hello": "Bonjour",
  "cancel": "Annuler",
  "confirm": "Confirmer",
  "squirrel": "Squirrel",
  "client": "Client",
  "trackId": "Numéro de suivi",
  "createOrder": "Créer une commande",
  "editOrder": "Editer la commande",
  "shopName": "Nom du magasin",
  "productName": "Nom du produit",
  "orderDate": "Date de la commande",
  "orderStatus": "Statut de la commande",
  "orderTotal": "Total de la commande",
  "orderActions": "Actions de la commande",
  "orderAmount": "Montant de la commande",
  "commission": "Commission",
  "internalFees": "Frais internes",
  "percentage": "Pourcentage",
  "amount": "Montant",
  "method": "Méthode",
  "intermediary": "Intermédiaire",
  "comment": "Commentaire",
  "save": "Sauvegarder",
  "days": "Jours",
  "euros": "€",
  "clientName": "Nom du client",
  "orderDuration": "Durée de la commande",
  "useConditions": "Conditions d'utilisation",
  "useConditions1": "1) Chaque clé de licence est unique, valide 30 jours et utilisable par un seul utilisateur.",
  "useConditions2": "2) Si vous communiquez votre clé de licence à un tiers, la clé sera bannie et ne pourra plus être utilisée. Vous perderez alors l'accès à l'application et ne serez pas remboursé.",
  "useConditions3": "3) Si vous perdez votre clé de licence, vous ne pourrez pas la récupérer. Vous devrez alors acheter une nouvelle clé de licence.",
  "useConditions4": "4) Si vous perdez accès à votre appareil, nous ne pourrons d'aucune façon vous aider à récupérer vos données. (cf règle 3)",
  "useConditions5": "5) Les développeurs de cette application ne sont pas responsables, garants, approbateurs, commanditaires ou autre de l'utilisation ou la finalité de cette application.",
  "useConditions6": "6) Nous n'approuvons aucune activité illégale ou non conforme à la législation en vigueur.",
  "useConditions7": "7) Les développeurs de cette application souhaite correspondre aux besoins de ses utilisateurs. Si vous avez des suggestions, des questions ou des problèmes, veuillez contacter votre fournisseur.",
  "addOrderAction": "Ajouter une nouvelle action",
  "orderActionNameRequired": "Le nom de l'action est obligatoire",
  "orderActionName": "Nom de l'action",
  "orderActionDateRequired": "La date de l'action est obligatoire",
  "selectOrderActionDate": "Sélectionner la date de l'action",
  "add": "Ajouter",
  "pleaseEnterYourAccountNumber": "Veuillez entrer votre numéro de compte",
  "ifYouHaveLostYourKey": "Si vous avez perdu votre clé, contactez votre fournisseur.",
  "login": "Connexion",
  "impossibleToConnect": "Impossible de se connecter",
  "totalOrders": "Total des commandes",
  "totalAmount": "Total des montants",
  "totalCommissions": "Total des commissions",
  "noOrdersFound": "Aucune commande trouvée",
  "priceWithSymbol": "{}€",
  "open": "Ouvrir",
  "pinnedOrders": "Commandes épinglées",
  "pin": "Épingler",
  "orders": "Commandes",
  "hide": "Masquer",
  "select": "Sélectionner",
  "totalWithDate": "Total du mois de {}",
  "total": "Total",
  "nextAction": "Prochaine action",
  "noNextAction": "Aucune action à venir",
  "clickToSeeDetails": "Cliquer pour voir les détails",
  "ordersHistory": "Historique des commandes",
  "delete": "Supprimer",
  "shop": "Boutique",
  "product": "Produit",
  "margin": "Marge",
  "deleteOrder": "Supprimer la commande",
  "addOrderActionFuture": "Pour ajouter une action future il suffit d'ajouter une action avec une date supérieur à celle d'aujourd'hui. Par exemple {}",
  "actionsHistory": "Historique des actions",
  "noOrderAction": "Aucune action n'a été effectuée",
  "daysSinceLastAction": "Jours depuis la dernière action",
  "daysDiffWithSymbol": "+{} jours",
  "informations": "Informations",
  "trackingNumber": "Numéro de suivi",
  "endOfFile": "Fin de dossier prévue",
  "fees": "Frais",
  "contactShopByMail": "Recontacter la boutique par mail",
  "clickToChangePriority": "Cliquer pour changer la priorité",
  "priority": "Priorité",
  "clickToChangeStatus": "Pour changer le statut de la commande, veuillez cliquer sur le statut souhaité",
  "numberOfOrders": "Nombre de commandes",
  "sponsorship": "Parrainage",
  "firstOrder": "Première commande",
  "backToDashboard": "Retour au dashboard",
  "orderDetails": "Détails de la commande",
  "deleteOrderConfirmation": "Voulez-vous vraiment supprimer la commande ?\nCette action est irréversible.",
  "comingSoon": "Fonctionnalités à venir",
  "date": "Date",
  "name": "Nom",
  "destination": "Destination",
  "description": "Description",
  "parameters": "Paramètres",
  "ordersByDay": "Nombre de commandes par jour",
  "dailyRevenue": "Revenus journalier",
  "bestShops": "Boutiques les plus performantes",
  "bestProducts": "Produits les plus performants",
  "bestClient": "Client le plus fidèle",
  "mostFrequentClient": "Client le plus fréquent",
  "totalOrdersAmount": "Montant total des commandes",
  "yourLicenseWillExpireIn": "Votre licence expire dans {} {}",
  "hours": "heures",
  "contactYourProviderToRenew": "Contactez votre fournisseur pour la renouveler",
  "requestWeb": "Requête web",
  "home": "Accueil",
  "todoList": "Todo liste",
  "stats": "Statistiques",
  "planification": "Planification",
  "clients": "Clients",
  "history": "Historique",
  "noClients": "Aucun client trouvé",
  "percentageSymbol": "%"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"fr": _fr};
}
